<?php
$langs = [
  'sv' => [
    'title' => 'Lösenordsgenerator',
    'metaDescription' => 'Generera säkra lösenord och ordfraser direkt i webbläsaren med olika inställningar och exportfunktion.',
    'length' => 'Lösenordslängd (4–128)',
    'amount' => 'Antal att generera',
    'lower' => 'Små bokstäver',
    'upper' => 'Versaler',
    'numbers' => 'Siffror',
    'symbols' => 'Symboler',
    'passphrase' => 'Använd ordfras',
    'generate' => 'Generera',
    'export' => 'Exportera',
    'reset' => 'Rensa resultat',
    'copy' => 'Kopiera lösenord',
    'refresh' => 'Generera nytt lösenord',
    'copied' => 'Lösenord kopierat!',

    // README
    'readme_title' => 'Om Lösenordsgeneratorn',
    'readme_intro' => 'Skapa starka lösenord direkt i webbläsaren – inget skickas till servern. Perfekt för utvecklare, administratörer och alla som vill öka sin säkerhet.',
    'purpose_title' => 'Syfte',
    'purpose_text' => 'Detta verktyg är skapat för att snabbt generera starka lösenord direkt i webbläsaren, utan att data skickas någonstans. All generering sker lokalt – inget skickas till någon server. Du har full kontroll över vilka teckentyper som ska användas och hur långt lösenordet ska vara.',
    'how_title' => 'Så fungerar det',
    'how_list' => [
      'Ställ in önskad <strong>lösenordslängd</strong> (4–128 tecken).',
      'Välj vilka <strong>teckentyper</strong> som ska användas:<ul><li>Små bokstäver (a–z)</li><li>Stora bokstäver (A–Z)</li><li>Siffror (0–9)</li><li>Specialtecken (!@#$%^...)</li></ul>',
      'Välj antal lösenord att generera.',
      'Du kan även välja att generera minnesvänliga <strong>ordfraser</strong>.',
      'Klicka på <strong>Generera</strong>.',
    ],
    'preview_title' => 'Förhandslösenord',
    'preview_text' => 'Ovanför inställningarna visas alltid ett färskt <strong>förhandslösenord</strong> baserat på nuvarande inställningar. Du kan kopiera det direkt eller generera om det med ett klick. Förhandslösenordet uppdateras automatiskt när du ändrar inställningar – perfekt för snabb testning!',
    'export_title' => 'Export',
    'export_text' => 'När lösenord har genererats kan du exportera dem som <strong>JSON</strong>, <strong>CSV</strong> eller <strong>TXT</strong>. Exportknappen visas automatiskt efter första genereringen. Exporten är praktisk för t.ex. testdata eller import till andra system.',
    'strength_title' => 'Styrkeindikator',
    'strength_text' => 'Varje lösenord bedöms med en <strong>styrketagg</strong> som syns till höger om lösenordet i tabellen. Bedömningen baseras på två faktorer:',
    'strength_list' => [
      '<strong>Längd:</strong> Ju längre lösenord, desto bättre skydd mot brute-force-angrepp.',
      '<strong>Variation:</strong> Kombination av små/stora bokstäver, siffror och symboler gör det exponentiellt svårare att gissa.',
    ],
    'strength_info' => 'Ju fler möjliga tecken och ju längre lösenord, desto högre entropi – det vill säga, desto svårare för en angripare att gissa eller brute-forca ditt lösenord.',
    'strength_table' => [
      ['Svag', 'Kortare än 10 tecken eller bara 1–2 teckentyper', '<code>abcd1234</code>, <code>Password</code>'],
      ['Medel', 'Minst 10 tecken och minst 3 teckentyper', '<code>Abc123!xyz</code>'],
      ['Stark', 'Minst 14 tecken och alla fyra teckentyper', '<code>9fL!vGd@T6$WbZp1rU2x</code>'],
    ],
    'strength_warning' => 'Lösenordsstyrka påverkas <em>inte</em> av ordlistor, men du bör ändå undvika verkliga ord och personliga data.',
    'tips_title' => 'Tips för bättre lösenord',
    'tips_list' => [
      'Använd minst 12 tecken – gärna fler',
      'Inkludera alla fyra teckentyper',
      'Skapa olika lösenord för olika tjänster',
      'Använd en lösenordshanterare för att spara säkert',
      'En lång ordfras (t.ex. tre eller fler slumpmässiga ord) är ofta både stark och lätt att minnas',
    ],
    'example_title' => 'Exempel',
    'example_code' => "Längd: 24\nTecken: Små + Stora + Siffror + Symboler\n\nResultat:\nLösenord                 | Styrka\n-------------------------|---------\nKD4@n>acqZ0UYxtW7^!igfH[ | Stark\nMjukplast-Brusa          | Bra (ordfras)",
    'passphrase_title' => 'Om ordfraser',
    'passphrase_text' => 'Om du väljer <strong>Använd ordfras</strong> genereras lösenord som består av slumpmässigt valda svenska ord, ibland hopslagna med bindestreck. Verktyget försöker alltid skapa en fras med minst två ord, så länge det får plats inom den längd du valt. Om det inte går att få in två ord (t.ex. om längden är låg eller orden är långa) används ett ord istället.',
    'passphrase_list' => [
      'Ord väljs slumpmässigt från en svensk ordlista.',
      'Bindestreck används mellan orden om fler än ett ord får plats.',
      'Försök alltid använda så lång fras som möjligt för bättre säkerhet.',
    ],
    'passphrase_info' => '<strong>Tips:</strong> Öka längden för att få fler ord i frasen och därmed högre säkerhet!',
    'didyouknow_title' => 'Visste du att?',
    'didyouknow_list' => [
      'En brute-force-attack mot ett 16-tecken långt lösenord med alla teckentyper skulle ta längre tid än universums ålder – om du använder rätt generator!',
      'Ordfraser blev populära efter XKCD:s klassiska serie om "correct horse battery staple".',
      'Alla lösenord genereras med JavaScript direkt i din webbläsare – ingen risk för dataläckor.',
    ],
    'footer' => '© Mackan.eu – Dokumentation uppdaterad 2025-06-15',
    'tippy_copy' => 'Kopiera lösenord',
    'tippy_refresh' => 'Generera nytt lösenord',
    'tippy_export' => 'Exportera',
    'tippy_reset' => 'Rensa resultat',
    'tippy_copy_code' => 'Kopiera kod',
    'strength_headers' => ['Styrka', 'Kriterier', 'Exempel'],
    'strength_tags' => ['Svag', 'Medel', 'Stark'],
    'strength_good_phrase' => 'Bra (ordfras)',
  ],
  'en' => [
    'title' => 'Password Generator',
    'metaDescription' => 'Generate secure passwords and passphrases in your browser with various settings and export function.',
    'length' => 'Password length (4–128)',
    'amount' => 'Amount to generate',
    'lower' => 'Lowercase letters',
    'upper' => 'Uppercase letters',
    'numbers' => 'Numbers',
    'symbols' => 'Symbols',
    'passphrase' => 'Use passphrase',
    'generate' => 'Generate',
    'export' => 'Export',
    'reset' => 'Clear results',
    'copy' => 'Copy password',
    'refresh' => 'Generate new password',
    'copied' => 'Password copied!',

    // README
    'readme_title' => 'About the Password Generator',
    'readme_intro' => 'Create strong passwords directly in your browser – nothing is sent to the server. Perfect for developers, administrators, and anyone who wants to increase their security.',
    'purpose_title' => 'Purpose',
    'purpose_text' => 'This tool is designed to quickly generate strong passwords directly in your browser, with no data sent anywhere. All generation is local – nothing is sent to any server. You have full control over which character types to use and the password length.',
    'how_title' => 'How it works',
    'how_list' => [
      'Set the desired <strong>password length</strong> (4–128 characters).',
      'Choose which <strong>character types</strong> to use:<ul><li>Lowercase letters (a–z)</li><li>Uppercase letters (A–Z)</li><li>Numbers (0–9)</li><li>Special characters (!@#$%^...)</li></ul>',
      'Choose how many passwords to generate.',
      'You can also choose to generate memorable <strong>passphrases</strong>.',
      'Click <strong>Generate</strong>.',
    ],
    'preview_title' => 'Password Preview',
    'preview_text' => 'Above the settings, a fresh <strong>preview password</strong> is always shown based on the current settings. You can copy it directly or generate a new one with a click. The preview password updates automatically when you change settings – perfect for quick testing!',
    'export_title' => 'Export',
    'export_text' => 'When passwords have been generated, you can export them as <strong>JSON</strong>, <strong>CSV</strong> or <strong>TXT</strong>. The export button appears automatically after the first generation. Export is useful for e.g. test data or import into other systems.',
    'strength_title' => 'Strength Indicator',
    'strength_text' => 'Each password is rated with a <strong>strength tag</strong> shown to the right of the password in the table. The rating is based on two factors:',
    'strength_list' => [
      '<strong>Length:</strong> The longer the password, the better protection against brute-force attacks.',
      '<strong>Variation:</strong> Combining lowercase/uppercase letters, numbers and symbols makes it exponentially harder to guess.',
    ],
    'strength_info' => 'The more possible characters and the longer the password, the higher the entropy – meaning it is harder for an attacker to guess or brute-force your password.',
    'strength_table' => [
      ['Weak', 'Shorter than 10 characters or only 1–2 character types', '<code>abcd1234</code>, <code>Password</code>'],
      ['Medium', 'At least 10 characters and at least 3 character types', '<code>Abc123!xyz</code>'],
      ['Strong', 'At least 14 characters and all four character types', '<code>9fL!vGd@T6$WbZp1rU2x</code>'],
    ],
    'strength_warning' => 'Password strength is <em>not</em> affected by dictionary words, but you should still avoid real words and personal data.',
    'tips_title' => 'Tips for better passwords',
    'tips_list' => [
      'Use at least 12 characters – preferably more',
      'Include all four character types',
      'Create different passwords for different services',
      'Use a password manager to store them securely',
      'A long passphrase (e.g. three or more random words) is often both strong and easy to remember',
    ],
    'example_title' => 'Example',
    'example_code' => "Length: 24\nCharacters: Lowercase + Uppercase + Numbers + Symbols\n\nResult:\nPassword                 | Strength\n-------------------------|---------\nKD4@n>acqZ0UYxtW7^!igfH[ | Strong\nMjukplast-Brusa          | Good (passphrase)",
    'passphrase_title' => 'About passphrases',
    'passphrase_text' => 'If you select <strong>Use passphrase</strong>, passwords will be generated from randomly chosen Swedish words, sometimes joined with hyphens. The tool always tries to create a phrase with at least two words, as long as it fits within your chosen length. If not possible (e.g. if the length is low or words are long), a single word is used instead.',
    'passphrase_list' => [
      'Words are randomly selected from a Swedish word list.',
      'Hyphens are used between words if more than one word fits.',
      'Always try to use as long a phrase as possible for better security.',
    ],
    'passphrase_info' => '<strong>Tip:</strong> Increase the length to fit more words in the phrase and thus higher security!',
    'didyouknow_title' => 'Did you know?',
    'didyouknow_list' => [
      'A brute-force attack on a 16-character password with all character types would take longer than the age of the universe – if you use the right generator!',
      'Passphrases became popular after XKCD’s classic comic about "correct horse battery staple".',
      'All passwords are generated with JavaScript directly in your browser – no risk of data leaks.',
    ],
    'footer' => '© Mackan.eu – Documentation updated 2025-06-15',
    'tippy_copy' => 'Copy password',
    'tippy_refresh' => 'Generate new password',
    'tippy_export' => 'Export',
    'tippy_reset' => 'Clear results',
    'tippy_copy_code' => 'Copy code',
    'strength_headers' => ['Strength', 'Criteria', 'Example'],
    'strength_tags' => ['Weak', 'Medium', 'Strong'],
    'strength_good_phrase' => 'Good (passphrase)',
  ]
];
